//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 1.5
// Date Of Creation: 11/5/2013 1:51:25 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>
#import "catalogProductTierPriceEntity.h"
#import "associativeEntity.h"


@interface catalogProductReturnEntity : NSObject
{
}
@property (nonatomic, copy) NSString *product_id;
@property (nonatomic, copy) NSString *sku;
@property (nonatomic, copy) NSString *set;
@property (nonatomic, copy) NSString *type;
@property (nonatomic, strong) NSMutableArray *categories;
@property (nonatomic, strong) NSMutableArray *websites;
@property (nonatomic, copy) NSString *created_at;
@property (nonatomic, copy) NSString *updated_at;
@property (nonatomic, copy) NSString *type_id;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *desc;
@property (nonatomic, copy) NSString *short_description;
@property (nonatomic, copy) NSString *weight;
@property (nonatomic, copy) NSString *status;
@property (nonatomic, copy) NSString *url_key;
@property (nonatomic, copy) NSString *url_path;
@property (nonatomic, copy) NSString *visibility;
@property (nonatomic, strong) NSMutableArray *category_ids;
@property (nonatomic, strong) NSMutableArray *website_ids;
@property (nonatomic, copy) NSString *has_options;
@property (nonatomic, copy) NSString *gift_message_available;
@property (nonatomic, copy) NSString *price;
@property (nonatomic, copy) NSString *special_price;
@property (nonatomic, copy) NSString *special_from_date;
@property (nonatomic, copy) NSString *special_to_date;
@property (nonatomic, copy) NSString *tax_class_id;
@property (nonatomic, strong) NSMutableArray *tier_price;
@property (nonatomic, copy) NSString *meta_title;
@property (nonatomic, copy) NSString *meta_keyword;
@property (nonatomic, copy) NSString *meta_description;
@property (nonatomic, copy) NSString *custom_design;
@property (nonatomic, copy) NSString *custom_layout_update;
@property (nonatomic, copy) NSString *options_container;
@property (nonatomic, strong) NSMutableArray *additional_attributes;
@property (nonatomic, copy) NSString *enable_googlecheckout;

-(NSString*)toString:(BOOL)addNameWrap;
-(id)initWithArray:(NSArray*)array;
-(void)encodeWithCoder:(NSCoder *)encoder;
-(id)copyWithZone:(NSZone *)zone;
-(id)initWithCoder:(NSCoder *)decoder;
@end
