//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 1.5
// Date Of Creation: 11/5/2013 1:51:25 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import "catalogCategoryTree.h" 


@implementation catalogCategoryTree

-(id)initWithArray:(NSArray*)array {
    self = [super init];
    if (self) {
        @try {
            for (int i0 = 0; i0 < [array count]; i0++)
            {
                if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"category_id"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setCategory_id:[nodeContentValue intValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"parent_id"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setParent_id:[nodeContentValue intValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"name"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setName:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"position"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setPosition:[nodeContentValue intValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"level"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setLevel:[nodeContentValue intValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeChildArray"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"children"]==NSOrderedSame)){
                    NSArray* array1= [[array objectAtIndex:i0] objectForKey:@"nodeChildArray"];
                    NSMutableArray* dataArray1= [[NSMutableArray alloc]init];
                    for (int i1=0; i1<[array1 count];i1++)
                    {
                        NSArray* arrayXml = [[array1  objectAtIndex:i1] objectForKey:@"nodeChildArray"];
                        catalogCategoryEntity* item = [[catalogCategoryEntity alloc] initWithArray:arrayXml];
                        [dataArray1  addObject:item];
                    }
                    [self setChildren:dataArray1];
                }
            }
        }
        @catch(NSException *ex){
        }
    }
    return self;
}
-(NSString*)toString:(BOOL)addNameWrap {
    NSMutableString *nsString = [NSMutableString string];
    if (addNameWrap == YES)
        [nsString appendString:@"<catalogCategoryTree>" ];
    [nsString appendFormat:@"<category_id>%d</category_id>" , [self category_id]];
    [nsString appendFormat:@"<parent_id>%d</parent_id>" , [self parent_id]];
    if (self.name != nil) {
        [nsString appendFormat:@"<name>%@</name>" , [self name]];
    }
    [nsString appendFormat:@"<position>%d</position>" , [self position]];
    [nsString appendFormat:@"<level>%d</level>" , [self level]];
    if (self.children != nil) {
        [nsString appendFormat:@"<children>"];
        for(catalogCategoryEntity *elm in self.children){
            [nsString appendFormat:@"%@", [elm toString:YES]];
        }
        [nsString appendFormat:@"</children>"];
    }
    if (addNameWrap == YES)
        [nsString appendString:@"</catalogCategoryTree>" ];
    return nsString;
}
#pragma mark - NSCoding
-(id)initWithCoder:(NSCoder *)decoder{
    self = [super init];
    if (self){
        self.category_id = [decoder decodeInt32ForKey:@"category_id"];
        self.parent_id = [decoder decodeInt32ForKey:@"parent_id"];
        self.name = [decoder decodeObjectForKey:@"name"];
        self.position = [decoder decodeInt32ForKey:@"position"];
        self.level = [decoder decodeInt32ForKey:@"level"];
        self.children = [decoder decodeObjectForKey:@"children"];
    }
    return self;
}
-(void)encodeWithCoder:(NSCoder *)encoder{
    [encoder encodeInt32:self.category_id forKey:@"category_id"];
    [encoder encodeInt32:self.parent_id forKey:@"parent_id"];
    [encoder encodeObject:self.name forKey:@"name"];
    [encoder encodeInt32:self.position forKey:@"position"];
    [encoder encodeInt32:self.level forKey:@"level"];
    [encoder encodeObject:self.children forKey:@"children"];
}
-(id)copyWithZone:(NSZone *)zone {
    catalogCategoryTree *finalCopy = [[[self class] allocWithZone: zone] init];
    
    finalCopy.category_id = self.category_id;
    
    finalCopy.parent_id = self.parent_id;
    
    NSString *copy3 = [self.name copy];
    finalCopy.name = copy3;
    
    finalCopy.position = self.position;
    
    finalCopy.level = self.level;
    
    NSMutableArray *cpy6 = [self.children copy];
    finalCopy.children = cpy6;
    
    return finalCopy;
}

@end
