//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 1.5
// Date Of Creation: 11/5/2013 1:51:25 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import "catalogProductReturnEntity.h" 


@implementation catalogProductReturnEntity

-(id)initWithArray:(NSArray*)array {
    self = [super init];
    if (self) {
        @try {
            for (int i0 = 0; i0 < [array count]; i0++)
            {
                if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"product_id"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setProduct_id:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"sku"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setSku:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"set"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setSet:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"type"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setType:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeChildArray"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"categories"]==NSOrderedSame)){
                    NSArray* array1= [[array objectAtIndex:i0] objectForKey:@"nodeChildArray"];
                    NSMutableArray* dataArray1= [[NSMutableArray alloc]init];
                    for (int i1=0; i1<[array1 count];i1++)
                    {
                        NSString* item = [[NSString alloc] initWithString:[[array1 objectAtIndex:i1] objectForKey:@"nodeContent"]];
                        [dataArray1  addObject:item];
                    }
                    [self setCategories:dataArray1];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeChildArray"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"websites"]==NSOrderedSame)){
                    NSArray* array1= [[array objectAtIndex:i0] objectForKey:@"nodeChildArray"];
                    NSMutableArray* dataArray1= [[NSMutableArray alloc]init];
                    for (int i1=0; i1<[array1 count];i1++)
                    {
                        NSString* item = [[NSString alloc] initWithString:[[array1 objectAtIndex:i1] objectForKey:@"nodeContent"]];
                        [dataArray1  addObject:item];
                    }
                    [self setWebsites:dataArray1];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"created_at"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCreated_at:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"updated_at"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setUpdated_at:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"type_id"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setType_id:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"name"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setName:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"description"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setDescription:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"short_description"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setShort_description:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"weight"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setWeight:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"status"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setStatus:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"url_key"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setUrl_key:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"url_path"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setUrl_path:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"visibility"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setVisibility:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeChildArray"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"category_ids"]==NSOrderedSame)){
                    NSArray* array1= [[array objectAtIndex:i0] objectForKey:@"nodeChildArray"];
                    NSMutableArray* dataArray1= [[NSMutableArray alloc]init];
                    for (int i1=0; i1<[array1 count];i1++)
                    {
                        NSString* item = [[NSString alloc] initWithString:[[array1 objectAtIndex:i1] objectForKey:@"nodeContent"]];
                        [dataArray1  addObject:item];
                    }
                    [self setCategory_ids:dataArray1];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeChildArray"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"website_ids"]==NSOrderedSame)){
                    NSArray* array1= [[array objectAtIndex:i0] objectForKey:@"nodeChildArray"];
                    NSMutableArray* dataArray1= [[NSMutableArray alloc]init];
                    for (int i1=0; i1<[array1 count];i1++)
                    {
                        NSString* item = [[NSString alloc] initWithString:[[array1 objectAtIndex:i1] objectForKey:@"nodeContent"]];
                        [dataArray1  addObject:item];
                    }
                    [self setWebsite_ids:dataArray1];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"has_options"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setHas_options:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"gift_message_available"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setGift_message_available:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"price"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setPrice:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"special_price"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setSpecial_price:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"special_from_date"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setSpecial_from_date:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"special_to_date"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setSpecial_to_date:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"tax_class_id"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setTax_class_id:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeChildArray"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"tier_price"]==NSOrderedSame)){
                    NSArray* array1= [[array objectAtIndex:i0] objectForKey:@"nodeChildArray"];
                    NSMutableArray* dataArray1= [[NSMutableArray alloc]init];
                    for (int i1=0; i1<[array1 count];i1++)
                    {
                        NSArray* arrayXml = [[array1  objectAtIndex:i1] objectForKey:@"nodeChildArray"];
                        catalogProductTierPriceEntity* item = [[catalogProductTierPriceEntity alloc] initWithArray:arrayXml];
                        [dataArray1  addObject:item];
                    }
                    [self setTier_price:dataArray1];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"meta_title"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setMeta_title:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"meta_keyword"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setMeta_keyword:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"meta_description"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setMeta_description:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"custom_design"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCustom_design:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"custom_layout_update"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCustom_layout_update:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"options_container"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setOptions_container:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeChildArray"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"additional_attributes"]==NSOrderedSame)){
                    NSArray* array1= [[array objectAtIndex:i0] objectForKey:@"nodeChildArray"];
                    NSMutableArray* dataArray1= [[NSMutableArray alloc]init];
                    for (int i1=0; i1<[array1 count];i1++)
                    {
                        NSArray* arrayXml = [[array1  objectAtIndex:i1] objectForKey:@"nodeChildArray"];
                        associativeEntity* item = [[associativeEntity alloc] initWithArray:arrayXml];
                        [dataArray1  addObject:item];
                    }
                    [self setAdditional_attributes:dataArray1];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"enable_googlecheckout"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setEnable_googlecheckout:nodeContentValue];
                }
            }
        }
        @catch(NSException *ex){
        }
    }
    return self;
}
-(NSString*)toString:(BOOL)addNameWrap {
    NSMutableString *nsString = [NSMutableString string];
    if (addNameWrap == YES)
        [nsString appendString:@"<catalogProductReturnEntity>" ];
    if (self.product_id != nil) {
        [nsString appendFormat:@"<product_id>%@</product_id>" , [self product_id]];
    }
    if (self.sku != nil) {
        [nsString appendFormat:@"<sku>%@</sku>" , [self sku]];
    }
    if (self.set != nil) {
        [nsString appendFormat:@"<set>%@</set>" , [self set]];
    }
    if (self.type != nil) {
        [nsString appendFormat:@"<type>%@</type>" , [self type]];
    }
    if (self.categories != nil) {
        [nsString appendFormat:@"<categories>"];
        for(NSString *elm in self.categories){
            [nsString appendFormat:@"<string>%@</string>", elm];
        }
        [nsString appendFormat:@"</categories>"];
    }
    if (self.websites != nil) {
        [nsString appendFormat:@"<websites>"];
        for(NSString *elm in self.websites){
            [nsString appendFormat:@"<string>%@</string>", elm];
        }
        [nsString appendFormat:@"</websites>"];
    }
    if (self.created_at != nil) {
        [nsString appendFormat:@"<created_at>%@</created_at>" , [self created_at]];
    }
    if (self.updated_at != nil) {
        [nsString appendFormat:@"<updated_at>%@</updated_at>" , [self updated_at]];
    }
    if (self.type_id != nil) {
        [nsString appendFormat:@"<type_id>%@</type_id>" , [self type_id]];
    }
    if (self.name != nil) {
        [nsString appendFormat:@"<name>%@</name>" , [self name]];
    }
    if (self.description != nil) {
        [nsString appendFormat:@"<description>%@</description>" , [self description]];
    }
    if (self.short_description != nil) {
        [nsString appendFormat:@"<short_description>%@</short_description>" , [self short_description]];
    }
    if (self.weight != nil) {
        [nsString appendFormat:@"<weight>%@</weight>" , [self weight]];
    }
    if (self.status != nil) {
        [nsString appendFormat:@"<status>%@</status>" , [self status]];
    }
    if (self.url_key != nil) {
        [nsString appendFormat:@"<url_key>%@</url_key>" , [self url_key]];
    }
    if (self.url_path != nil) {
        [nsString appendFormat:@"<url_path>%@</url_path>" , [self url_path]];
    }
    if (self.visibility != nil) {
        [nsString appendFormat:@"<visibility>%@</visibility>" , [self visibility]];
    }
    if (self.category_ids != nil) {
        [nsString appendFormat:@"<category_ids>"];
        for(NSString *elm in self.category_ids){
            [nsString appendFormat:@"<string>%@</string>", elm];
        }
        [nsString appendFormat:@"</category_ids>"];
    }
    if (self.website_ids != nil) {
        [nsString appendFormat:@"<website_ids>"];
        for(NSString *elm in self.website_ids){
            [nsString appendFormat:@"<string>%@</string>", elm];
        }
        [nsString appendFormat:@"</website_ids>"];
    }
    if (self.has_options != nil) {
        [nsString appendFormat:@"<has_options>%@</has_options>" , [self has_options]];
    }
    if (self.gift_message_available != nil) {
        [nsString appendFormat:@"<gift_message_available>%@</gift_message_available>" , [self gift_message_available]];
    }
    if (self.price != nil) {
        [nsString appendFormat:@"<price>%@</price>" , [self price]];
    }
    if (self.special_price != nil) {
        [nsString appendFormat:@"<special_price>%@</special_price>" , [self special_price]];
    }
    if (self.special_from_date != nil) {
        [nsString appendFormat:@"<special_from_date>%@</special_from_date>" , [self special_from_date]];
    }
    if (self.special_to_date != nil) {
        [nsString appendFormat:@"<special_to_date>%@</special_to_date>" , [self special_to_date]];
    }
    if (self.tax_class_id != nil) {
        [nsString appendFormat:@"<tax_class_id>%@</tax_class_id>" , [self tax_class_id]];
    }
    if (self.tier_price != nil) {
        [nsString appendFormat:@"<tier_price>"];
        for(catalogProductTierPriceEntity *elm in self.tier_price){
            [nsString appendFormat:@"%@", [elm toString:YES]];
        }
        [nsString appendFormat:@"</tier_price>"];
    }
    if (self.meta_title != nil) {
        [nsString appendFormat:@"<meta_title>%@</meta_title>" , [self meta_title]];
    }
    if (self.meta_keyword != nil) {
        [nsString appendFormat:@"<meta_keyword>%@</meta_keyword>" , [self meta_keyword]];
    }
    if (self.meta_description != nil) {
        [nsString appendFormat:@"<meta_description>%@</meta_description>" , [self meta_description]];
    }
    if (self.custom_design != nil) {
        [nsString appendFormat:@"<custom_design>%@</custom_design>" , [self custom_design]];
    }
    if (self.custom_layout_update != nil) {
        [nsString appendFormat:@"<custom_layout_update>%@</custom_layout_update>" , [self custom_layout_update]];
    }
    if (self.options_container != nil) {
        [nsString appendFormat:@"<options_container>%@</options_container>" , [self options_container]];
    }
    if (self.additional_attributes != nil) {
        [nsString appendFormat:@"<additional_attributes>"];
        for(associativeEntity *elm in self.additional_attributes){
            [nsString appendFormat:@"%@", [elm toString:YES]];
        }
        [nsString appendFormat:@"</additional_attributes>"];
    }
    if (self.enable_googlecheckout != nil) {
        [nsString appendFormat:@"<enable_googlecheckout>%@</enable_googlecheckout>" , [self enable_googlecheckout]];
    }
    if (addNameWrap == YES)
        [nsString appendString:@"</catalogProductReturnEntity>" ];
    return nsString;
}
#pragma mark - NSCoding
-(id)initWithCoder:(NSCoder *)decoder{
    self = [super init];
    if (self){
        self.product_id = [decoder decodeObjectForKey:@"product_id"];
        self.sku = [decoder decodeObjectForKey:@"sku"];
        self.set = [decoder decodeObjectForKey:@"set"];
        self.type = [decoder decodeObjectForKey:@"type"];
        self.categories = [decoder decodeObjectForKey:@"categories"];
        self.websites = [decoder decodeObjectForKey:@"websites"];
        self.created_at = [decoder decodeObjectForKey:@"created_at"];
        self.updated_at = [decoder decodeObjectForKey:@"updated_at"];
        self.type_id = [decoder decodeObjectForKey:@"type_id"];
        self.name = [decoder decodeObjectForKey:@"name"];
        self.description = [decoder decodeObjectForKey:@"description"];
        self.short_description = [decoder decodeObjectForKey:@"short_description"];
        self.weight = [decoder decodeObjectForKey:@"weight"];
        self.status = [decoder decodeObjectForKey:@"status"];
        self.url_key = [decoder decodeObjectForKey:@"url_key"];
        self.url_path = [decoder decodeObjectForKey:@"url_path"];
        self.visibility = [decoder decodeObjectForKey:@"visibility"];
        self.category_ids = [decoder decodeObjectForKey:@"category_ids"];
        self.website_ids = [decoder decodeObjectForKey:@"website_ids"];
        self.has_options = [decoder decodeObjectForKey:@"has_options"];
        self.gift_message_available = [decoder decodeObjectForKey:@"gift_message_available"];
        self.price = [decoder decodeObjectForKey:@"price"];
        self.special_price = [decoder decodeObjectForKey:@"special_price"];
        self.special_from_date = [decoder decodeObjectForKey:@"special_from_date"];
        self.special_to_date = [decoder decodeObjectForKey:@"special_to_date"];
        self.tax_class_id = [decoder decodeObjectForKey:@"tax_class_id"];
        self.tier_price = [decoder decodeObjectForKey:@"tier_price"];
        self.meta_title = [decoder decodeObjectForKey:@"meta_title"];
        self.meta_keyword = [decoder decodeObjectForKey:@"meta_keyword"];
        self.meta_description = [decoder decodeObjectForKey:@"meta_description"];
        self.custom_design = [decoder decodeObjectForKey:@"custom_design"];
        self.custom_layout_update = [decoder decodeObjectForKey:@"custom_layout_update"];
        self.options_container = [decoder decodeObjectForKey:@"options_container"];
        self.additional_attributes = [decoder decodeObjectForKey:@"additional_attributes"];
        self.enable_googlecheckout = [decoder decodeObjectForKey:@"enable_googlecheckout"];
    }
    return self;
}
-(void)encodeWithCoder:(NSCoder *)encoder{
    [encoder encodeObject:self.product_id forKey:@"product_id"];
    [encoder encodeObject:self.sku forKey:@"sku"];
    [encoder encodeObject:self.set forKey:@"set"];
    [encoder encodeObject:self.type forKey:@"type"];
    [encoder encodeObject:self.categories forKey:@"categories"];
    [encoder encodeObject:self.websites forKey:@"websites"];
    [encoder encodeObject:self.created_at forKey:@"created_at"];
    [encoder encodeObject:self.updated_at forKey:@"updated_at"];
    [encoder encodeObject:self.type_id forKey:@"type_id"];
    [encoder encodeObject:self.name forKey:@"name"];
    [encoder encodeObject:self.description forKey:@"description"];
    [encoder encodeObject:self.short_description forKey:@"short_description"];
    [encoder encodeObject:self.weight forKey:@"weight"];
    [encoder encodeObject:self.status forKey:@"status"];
    [encoder encodeObject:self.url_key forKey:@"url_key"];
    [encoder encodeObject:self.url_path forKey:@"url_path"];
    [encoder encodeObject:self.visibility forKey:@"visibility"];
    [encoder encodeObject:self.category_ids forKey:@"category_ids"];
    [encoder encodeObject:self.website_ids forKey:@"website_ids"];
    [encoder encodeObject:self.has_options forKey:@"has_options"];
    [encoder encodeObject:self.gift_message_available forKey:@"gift_message_available"];
    [encoder encodeObject:self.price forKey:@"price"];
    [encoder encodeObject:self.special_price forKey:@"special_price"];
    [encoder encodeObject:self.special_from_date forKey:@"special_from_date"];
    [encoder encodeObject:self.special_to_date forKey:@"special_to_date"];
    [encoder encodeObject:self.tax_class_id forKey:@"tax_class_id"];
    [encoder encodeObject:self.tier_price forKey:@"tier_price"];
    [encoder encodeObject:self.meta_title forKey:@"meta_title"];
    [encoder encodeObject:self.meta_keyword forKey:@"meta_keyword"];
    [encoder encodeObject:self.meta_description forKey:@"meta_description"];
    [encoder encodeObject:self.custom_design forKey:@"custom_design"];
    [encoder encodeObject:self.custom_layout_update forKey:@"custom_layout_update"];
    [encoder encodeObject:self.options_container forKey:@"options_container"];
    [encoder encodeObject:self.additional_attributes forKey:@"additional_attributes"];
    [encoder encodeObject:self.enable_googlecheckout forKey:@"enable_googlecheckout"];
}
-(id)copyWithZone:(NSZone *)zone {
    catalogProductReturnEntity *finalCopy = [[[self class] allocWithZone: zone] init];
    
    NSString *copy1 = [self.product_id copy];
    finalCopy.product_id = copy1;
    
    NSString *copy2 = [self.sku copy];
    finalCopy.sku = copy2;
    
    NSString *copy3 = [self.set copy];
    finalCopy.set = copy3;
    
    NSString *copy4 = [self.type copy];
    finalCopy.type = copy4;
    
    NSMutableArray *cpy5 = [self.categories copy];
    finalCopy.categories = cpy5;
    
    NSMutableArray *cpy6 = [self.websites copy];
    finalCopy.websites = cpy6;
    
    NSString *copy7 = [self.created_at copy];
    finalCopy.created_at = copy7;
    
    NSString *copy8 = [self.updated_at copy];
    finalCopy.updated_at = copy8;
    
    NSString *copy9 = [self.type_id copy];
    finalCopy.type_id = copy9;
    
    NSString *copy10 = [self.name copy];
    finalCopy.name = copy10;
    
    NSString *copy11 = [self.description copy];
    finalCopy.description = copy11;
    
    NSString *copy12 = [self.short_description copy];
    finalCopy.short_description = copy12;
    
    NSString *copy13 = [self.weight copy];
    finalCopy.weight = copy13;
    
    NSString *copy14 = [self.status copy];
    finalCopy.status = copy14;
    
    NSString *copy15 = [self.url_key copy];
    finalCopy.url_key = copy15;
    
    NSString *copy16 = [self.url_path copy];
    finalCopy.url_path = copy16;
    
    NSString *copy17 = [self.visibility copy];
    finalCopy.visibility = copy17;
    
    NSMutableArray *cpy18 = [self.category_ids copy];
    finalCopy.category_ids = cpy18;
    
    NSMutableArray *cpy19 = [self.website_ids copy];
    finalCopy.website_ids = cpy19;
    
    NSString *copy20 = [self.has_options copy];
    finalCopy.has_options = copy20;
    
    NSString *copy21 = [self.gift_message_available copy];
    finalCopy.gift_message_available = copy21;
    
    NSString *copy22 = [self.price copy];
    finalCopy.price = copy22;
    
    NSString *copy23 = [self.special_price copy];
    finalCopy.special_price = copy23;
    
    NSString *copy24 = [self.special_from_date copy];
    finalCopy.special_from_date = copy24;
    
    NSString *copy25 = [self.special_to_date copy];
    finalCopy.special_to_date = copy25;
    
    NSString *copy26 = [self.tax_class_id copy];
    finalCopy.tax_class_id = copy26;
    
    NSMutableArray *cpy27 = [self.tier_price copy];
    finalCopy.tier_price = cpy27;
    
    NSString *copy28 = [self.meta_title copy];
    finalCopy.meta_title = copy28;
    
    NSString *copy29 = [self.meta_keyword copy];
    finalCopy.meta_keyword = copy29;
    
    NSString *copy30 = [self.meta_description copy];
    finalCopy.meta_description = copy30;
    
    NSString *copy31 = [self.custom_design copy];
    finalCopy.custom_design = copy31;
    
    NSString *copy32 = [self.custom_layout_update copy];
    finalCopy.custom_layout_update = copy32;
    
    NSString *copy33 = [self.options_container copy];
    finalCopy.options_container = copy33;
    
    NSMutableArray *cpy34 = [self.additional_attributes copy];
    finalCopy.additional_attributes = cpy34;
    
    NSString *copy35 = [self.enable_googlecheckout copy];
    finalCopy.enable_googlecheckout = copy35;
    
    return finalCopy;
}

@end
