//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 1.5
// Date Of Creation: 11/5/2013 1:51:25 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import "customerAddressEntityItem.h" 


@implementation customerAddressEntityItem

-(id)initWithArray:(NSArray*)array {
    self = [super init];
    if (self) {
        @try {
            for (int i0 = 0; i0 < [array count]; i0++)
            {
                if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"customer_address_id"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setCustomer_address_id:[nodeContentValue intValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"customer_address_idSpecified"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setCustomer_address_idSpecified:[nodeContentValue boolValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"created_at"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCreated_at:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"updated_at"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setUpdated_at:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"increment_id"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setIncrement_id:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"city"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCity:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"company"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCompany:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"country_id"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCountry_id:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"fax"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setFax:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"firstname"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setFirstname:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"lastname"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setLastname:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"middlename"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setMiddlename:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"postcode"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setPostcode:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"prefix"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setPrefix:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"region"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setRegion:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"region_id"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setRegion_id:[nodeContentValue intValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"region_idSpecified"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setRegion_idSpecified:[nodeContentValue boolValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"street"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setStreet:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"suffix"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setSuffix:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"telephone"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setTelephone:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"is_default_billing"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setIs_default_billing:[nodeContentValue boolValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"is_default_billingSpecified"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setIs_default_billingSpecified:[nodeContentValue boolValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"is_default_shipping"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setIs_default_shipping:[nodeContentValue boolValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"is_default_shippingSpecified"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setIs_default_shippingSpecified:[nodeContentValue boolValue]];
                }
            }
        }
        @catch(NSException *ex){
        }
    }
    return self;
}
-(NSString*)toString:(BOOL)addNameWrap {
    NSMutableString *nsString = [NSMutableString string];
    if (addNameWrap == YES)
        [nsString appendString:@"<customerAddressEntityItem>" ];
    [nsString appendFormat:@"<customer_address_id>%d</customer_address_id>" , [self customer_address_id]];
    [nsString appendFormat:@"<customer_address_idSpecified>%d</customer_address_idSpecified>" , [self customer_address_idSpecified]];
    if (self.created_at != nil) {
        [nsString appendFormat:@"<created_at>%@</created_at>" , [self created_at]];
    }
    if (self.updated_at != nil) {
        [nsString appendFormat:@"<updated_at>%@</updated_at>" , [self updated_at]];
    }
    if (self.increment_id != nil) {
        [nsString appendFormat:@"<increment_id>%@</increment_id>" , [self increment_id]];
    }
    if (self.city != nil) {
        [nsString appendFormat:@"<city>%@</city>" , [self city]];
    }
    if (self.company != nil) {
        [nsString appendFormat:@"<company>%@</company>" , [self company]];
    }
    if (self.country_id != nil) {
        [nsString appendFormat:@"<country_id>%@</country_id>" , [self country_id]];
    }
    if (self.fax != nil) {
        [nsString appendFormat:@"<fax>%@</fax>" , [self fax]];
    }
    if (self.firstname != nil) {
        [nsString appendFormat:@"<firstname>%@</firstname>" , [self firstname]];
    }
    if (self.lastname != nil) {
        [nsString appendFormat:@"<lastname>%@</lastname>" , [self lastname]];
    }
    if (self.middlename != nil) {
        [nsString appendFormat:@"<middlename>%@</middlename>" , [self middlename]];
    }
    if (self.postcode != nil) {
        [nsString appendFormat:@"<postcode>%@</postcode>" , [self postcode]];
    }
    if (self.prefix != nil) {
        [nsString appendFormat:@"<prefix>%@</prefix>" , [self prefix]];
    }
    if (self.region != nil) {
        [nsString appendFormat:@"<region>%@</region>" , [self region]];
    }
    [nsString appendFormat:@"<region_id>%d</region_id>" , [self region_id]];
    [nsString appendFormat:@"<region_idSpecified>%d</region_idSpecified>" , [self region_idSpecified]];
    if (self.street != nil) {
        [nsString appendFormat:@"<street>%@</street>" , [self street]];
    }
    if (self.suffix != nil) {
        [nsString appendFormat:@"<suffix>%@</suffix>" , [self suffix]];
    }
    if (self.telephone != nil) {
        [nsString appendFormat:@"<telephone>%@</telephone>" , [self telephone]];
    }
    [nsString appendFormat:@"<is_default_billing>%d</is_default_billing>" , [self is_default_billing]];
    [nsString appendFormat:@"<is_default_billingSpecified>%d</is_default_billingSpecified>" , [self is_default_billingSpecified]];
    [nsString appendFormat:@"<is_default_shipping>%d</is_default_shipping>" , [self is_default_shipping]];
    [nsString appendFormat:@"<is_default_shippingSpecified>%d</is_default_shippingSpecified>" , [self is_default_shippingSpecified]];
    if (addNameWrap == YES)
        [nsString appendString:@"</customerAddressEntityItem>" ];
    return nsString;
}
#pragma mark - NSCoding
-(id)initWithCoder:(NSCoder *)decoder{
    self = [super init];
    if (self){
        self.customer_address_id = [decoder decodeInt32ForKey:@"customer_address_id"];
        self.customer_address_idSpecified = [decoder decodeInt32ForKey:@"customer_address_idSpecified"];
        self.created_at = [decoder decodeObjectForKey:@"created_at"];
        self.updated_at = [decoder decodeObjectForKey:@"updated_at"];
        self.increment_id = [decoder decodeObjectForKey:@"increment_id"];
        self.city = [decoder decodeObjectForKey:@"city"];
        self.company = [decoder decodeObjectForKey:@"company"];
        self.country_id = [decoder decodeObjectForKey:@"country_id"];
        self.fax = [decoder decodeObjectForKey:@"fax"];
        self.firstname = [decoder decodeObjectForKey:@"firstname"];
        self.lastname = [decoder decodeObjectForKey:@"lastname"];
        self.middlename = [decoder decodeObjectForKey:@"middlename"];
        self.postcode = [decoder decodeObjectForKey:@"postcode"];
        self.prefix = [decoder decodeObjectForKey:@"prefix"];
        self.region = [decoder decodeObjectForKey:@"region"];
        self.region_id = [decoder decodeInt32ForKey:@"region_id"];
        self.region_idSpecified = [decoder decodeInt32ForKey:@"region_idSpecified"];
        self.street = [decoder decodeObjectForKey:@"street"];
        self.suffix = [decoder decodeObjectForKey:@"suffix"];
        self.telephone = [decoder decodeObjectForKey:@"telephone"];
        self.is_default_billing = [decoder decodeInt32ForKey:@"is_default_billing"];
        self.is_default_billingSpecified = [decoder decodeInt32ForKey:@"is_default_billingSpecified"];
        self.is_default_shipping = [decoder decodeInt32ForKey:@"is_default_shipping"];
        self.is_default_shippingSpecified = [decoder decodeInt32ForKey:@"is_default_shippingSpecified"];
    }
    return self;
}
-(void)encodeWithCoder:(NSCoder *)encoder{
    [encoder encodeInt32:self.customer_address_id forKey:@"customer_address_id"];
    [encoder encodeInt32:self.customer_address_idSpecified forKey:@"customer_address_idSpecified"];
    [encoder encodeObject:self.created_at forKey:@"created_at"];
    [encoder encodeObject:self.updated_at forKey:@"updated_at"];
    [encoder encodeObject:self.increment_id forKey:@"increment_id"];
    [encoder encodeObject:self.city forKey:@"city"];
    [encoder encodeObject:self.company forKey:@"company"];
    [encoder encodeObject:self.country_id forKey:@"country_id"];
    [encoder encodeObject:self.fax forKey:@"fax"];
    [encoder encodeObject:self.firstname forKey:@"firstname"];
    [encoder encodeObject:self.lastname forKey:@"lastname"];
    [encoder encodeObject:self.middlename forKey:@"middlename"];
    [encoder encodeObject:self.postcode forKey:@"postcode"];
    [encoder encodeObject:self.prefix forKey:@"prefix"];
    [encoder encodeObject:self.region forKey:@"region"];
    [encoder encodeInt32:self.region_id forKey:@"region_id"];
    [encoder encodeInt32:self.region_idSpecified forKey:@"region_idSpecified"];
    [encoder encodeObject:self.street forKey:@"street"];
    [encoder encodeObject:self.suffix forKey:@"suffix"];
    [encoder encodeObject:self.telephone forKey:@"telephone"];
    [encoder encodeInt32:self.is_default_billing forKey:@"is_default_billing"];
    [encoder encodeInt32:self.is_default_billingSpecified forKey:@"is_default_billingSpecified"];
    [encoder encodeInt32:self.is_default_shipping forKey:@"is_default_shipping"];
    [encoder encodeInt32:self.is_default_shippingSpecified forKey:@"is_default_shippingSpecified"];
}
-(id)copyWithZone:(NSZone *)zone {
    customerAddressEntityItem *finalCopy = [[[self class] allocWithZone: zone] init];
    
    finalCopy.customer_address_id = self.customer_address_id;
    
    finalCopy.customer_address_idSpecified = self.customer_address_idSpecified;
    
    NSString *copy3 = [self.created_at copy];
    finalCopy.created_at = copy3;
    
    NSString *copy4 = [self.updated_at copy];
    finalCopy.updated_at = copy4;
    
    NSString *copy5 = [self.increment_id copy];
    finalCopy.increment_id = copy5;
    
    NSString *copy6 = [self.city copy];
    finalCopy.city = copy6;
    
    NSString *copy7 = [self.company copy];
    finalCopy.company = copy7;
    
    NSString *copy8 = [self.country_id copy];
    finalCopy.country_id = copy8;
    
    NSString *copy9 = [self.fax copy];
    finalCopy.fax = copy9;
    
    NSString *copy10 = [self.firstname copy];
    finalCopy.firstname = copy10;
    
    NSString *copy11 = [self.lastname copy];
    finalCopy.lastname = copy11;
    
    NSString *copy12 = [self.middlename copy];
    finalCopy.middlename = copy12;
    
    NSString *copy13 = [self.postcode copy];
    finalCopy.postcode = copy13;
    
    NSString *copy14 = [self.prefix copy];
    finalCopy.prefix = copy14;
    
    NSString *copy15 = [self.region copy];
    finalCopy.region = copy15;
    
    finalCopy.region_id = self.region_id;
    
    finalCopy.region_idSpecified = self.region_idSpecified;
    
    NSString *copy18 = [self.street copy];
    finalCopy.street = copy18;
    
    NSString *copy19 = [self.suffix copy];
    finalCopy.suffix = copy19;
    
    NSString *copy20 = [self.telephone copy];
    finalCopy.telephone = copy20;
    
    finalCopy.is_default_billing = self.is_default_billing;
    
    finalCopy.is_default_billingSpecified = self.is_default_billingSpecified;
    
    finalCopy.is_default_shipping = self.is_default_shipping;
    
    finalCopy.is_default_shippingSpecified = self.is_default_shippingSpecified;
    
    return finalCopy;
}

@end
