//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 1.5
// Date Of Creation: 11/5/2013 1:51:25 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>


@interface customerAddressEntityItem : NSObject
{
}
@property int customer_address_id;
@property BOOL customer_address_idSpecified;
@property (nonatomic, copy) NSString *created_at;
@property (nonatomic, copy) NSString *updated_at;
@property (nonatomic, copy) NSString *increment_id;
@property (nonatomic, copy) NSString *city;
@property (nonatomic, copy) NSString *company;
@property (nonatomic, copy) NSString *country_id;
@property (nonatomic, copy) NSString *fax;
@property (nonatomic, copy) NSString *firstname;
@property (nonatomic, copy) NSString *lastname;
@property (nonatomic, copy) NSString *middlename;
@property (nonatomic, copy) NSString *postcode;
@property (nonatomic, copy) NSString *prefix;
@property (nonatomic, copy) NSString *region;
@property int region_id;
@property BOOL region_idSpecified;
@property (nonatomic, copy) NSString *street;
@property (nonatomic, copy) NSString *suffix;
@property (nonatomic, copy) NSString *telephone;
@property BOOL is_default_billing;
@property BOOL is_default_billingSpecified;
@property BOOL is_default_shipping;
@property BOOL is_default_shippingSpecified;

-(NSString*)toString:(BOOL)addNameWrap;
-(id)initWithArray:(NSArray*)array;
-(void)encodeWithCoder:(NSCoder *)encoder;
-(id)copyWithZone:(NSZone *)zone;
-(id)initWithCoder:(NSCoder *)decoder;
@end
