//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 1.5
// Date Of Creation: 11/5/2013 1:51:25 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>


@interface customerCustomerEntity : NSObject
{
}
@property int customer_id;
@property BOOL customer_idSpecified;
@property (nonatomic, copy) NSString *created_at;
@property (nonatomic, copy) NSString *updated_at;
@property (nonatomic, copy) NSString *increment_id;
@property int store_id;
@property BOOL store_idSpecified;
@property int website_id;
@property BOOL website_idSpecified;
@property (nonatomic, copy) NSString *created_in;
@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *firstname;
@property (nonatomic, copy) NSString *middlename;
@property (nonatomic, copy) NSString *lastname;
@property int group_id;
@property BOOL group_idSpecified;
@property (nonatomic, copy) NSString *prefix;
@property (nonatomic, copy) NSString *suffix;
@property (nonatomic, copy) NSString *dob;
@property (nonatomic, copy) NSString *taxvat;
@property BOOL confirmation;
@property BOOL confirmationSpecified;
@property (nonatomic, copy) NSString *password_hash;

-(NSString*)toString:(BOOL)addNameWrap;
-(id)initWithArray:(NSArray*)array;
-(void)encodeWithCoder:(NSCoder *)encoder;
-(id)copyWithZone:(NSZone *)zone;
-(id)initWithCoder:(NSCoder *)decoder;
@end
