//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 1.5
// Date Of Creation: 11/5/2013 1:51:25 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>


@interface shoppingCartPaymentEntity : NSObject
{
}
@property (nonatomic, copy) NSString *payment_id;
@property (nonatomic, copy) NSString *created_at;
@property (nonatomic, copy) NSString *updated_at;
@property (nonatomic, copy) NSString *method;
@property (nonatomic, copy) NSString *cc_type;
@property (nonatomic, copy) NSString *cc_number_enc;
@property (nonatomic, copy) NSString *cc_last4;
@property (nonatomic, copy) NSString *cc_cid_enc;
@property (nonatomic, copy) NSString *cc_owner;
@property (nonatomic, copy) NSString *cc_exp_month;
@property (nonatomic, copy) NSString *cc_exp_year;
@property (nonatomic, copy) NSString *cc_ss_owner;
@property (nonatomic, copy) NSString *cc_ss_start_month;
@property (nonatomic, copy) NSString *cc_ss_start_year;
@property (nonatomic, copy) NSString *cc_ss_issue;
@property (nonatomic, copy) NSString *po_number;
@property (nonatomic, copy) NSString *additional_data;
@property (nonatomic, copy) NSString *additional_information;

-(NSString*)toString:(BOOL)addNameWrap;
-(id)initWithArray:(NSArray*)array;
-(void)encodeWithCoder:(NSCoder *)encoder;
-(id)copyWithZone:(NSZone *)zone;
-(id)initWithCoder:(NSCoder *)decoder;
@end
