//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 1.5
// Date Of Creation: 11/5/2013 1:51:25 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>
#import "associativeEntity.h"
#import "associativeEntity.h"
#import "associativeEntity.h"


@interface shoppingCartProductEntity : NSObject
{
}
@property (nonatomic, copy) NSString *product_id;
@property (nonatomic, copy) NSString *sku;
@property double qty;
@property BOOL qtySpecified;
@property (nonatomic, strong) NSMutableArray *options;
@property (nonatomic, strong) NSMutableArray *bundle_option;
@property (nonatomic, strong) NSMutableArray *bundle_option_qty;
@property (nonatomic, strong) NSMutableArray *links;

-(NSString*)toString:(BOOL)addNameWrap;
-(id)initWithArray:(NSArray*)array;
-(void)encodeWithCoder:(NSCoder *)encoder;
-(id)copyWithZone:(NSZone *)zone;
-(id)initWithCoder:(NSCoder *)decoder;
@end
