//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 1.5
// Date Of Creation: 11/5/2013 1:51:25 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>


@interface shoppingCartAddressEntity : NSObject
{
}
@property (nonatomic, copy) NSString *address_id;
@property (nonatomic, copy) NSString *created_at;
@property (nonatomic, copy) NSString *updated_at;
@property (nonatomic, copy) NSString *customer_id;
@property int save_in_address_book;
@property BOOL save_in_address_bookSpecified;
@property (nonatomic, copy) NSString *customer_address_id;
@property (nonatomic, copy) NSString *address_type;
@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *prefix;
@property (nonatomic, copy) NSString *firstname;
@property (nonatomic, copy) NSString *middlename;
@property (nonatomic, copy) NSString *lastname;
@property (nonatomic, copy) NSString *suffix;
@property (nonatomic, copy) NSString *company;
@property (nonatomic, copy) NSString *street;
@property (nonatomic, copy) NSString *city;
@property (nonatomic, copy) NSString *region;
@property (nonatomic, copy) NSString *region_id;
@property (nonatomic, copy) NSString *postcode;
@property (nonatomic, copy) NSString *country_id;
@property (nonatomic, copy) NSString *telephone;
@property (nonatomic, copy) NSString *fax;
@property int same_as_billing;
@property BOOL same_as_billingSpecified;
@property int free_shipping;
@property BOOL free_shippingSpecified;
@property (nonatomic, copy) NSString *shipping_method;
@property (nonatomic, copy) NSString *shipping_description;
@property double weight;
@property BOOL weightSpecified;

-(NSString*)toString:(BOOL)addNameWrap;
-(id)initWithArray:(NSArray*)array;
-(void)encodeWithCoder:(NSCoder *)encoder;
-(id)copyWithZone:(NSZone *)zone;
-(id)initWithCoder:(NSCoder *)decoder;
@end
