//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 1.5
// Date Of Creation: 11/5/2013 1:51:25 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import "shoppingCartPaymentEntity.h" 


@implementation shoppingCartPaymentEntity

-(id)initWithArray:(NSArray*)array {
    self = [super init];
    if (self) {
        @try {
            for (int i0 = 0; i0 < [array count]; i0++)
            {
                if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"payment_id"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setPayment_id:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"created_at"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCreated_at:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"updated_at"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setUpdated_at:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"method"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setMethod:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"cc_type"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCc_type:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"cc_number_enc"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCc_number_enc:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"cc_last4"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCc_last4:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"cc_cid_enc"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCc_cid_enc:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"cc_owner"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCc_owner:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"cc_exp_month"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCc_exp_month:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"cc_exp_year"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCc_exp_year:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"cc_ss_owner"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCc_ss_owner:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"cc_ss_start_month"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCc_ss_start_month:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"cc_ss_start_year"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCc_ss_start_year:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"cc_ss_issue"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCc_ss_issue:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"po_number"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setPo_number:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"additional_data"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setAdditional_data:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"additional_information"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setAdditional_information:nodeContentValue];
                }
            }
        }
        @catch(NSException *ex){
        }
    }
    return self;
}
-(NSString*)toString:(BOOL)addNameWrap {
    NSMutableString *nsString = [NSMutableString string];
    if (addNameWrap == YES)
        [nsString appendString:@"<shoppingCartPaymentEntity>" ];
    if (self.payment_id != nil) {
        [nsString appendFormat:@"<payment_id>%@</payment_id>" , [self payment_id]];
    }
    if (self.created_at != nil) {
        [nsString appendFormat:@"<created_at>%@</created_at>" , [self created_at]];
    }
    if (self.updated_at != nil) {
        [nsString appendFormat:@"<updated_at>%@</updated_at>" , [self updated_at]];
    }
    if (self.method != nil) {
        [nsString appendFormat:@"<method>%@</method>" , [self method]];
    }
    if (self.cc_type != nil) {
        [nsString appendFormat:@"<cc_type>%@</cc_type>" , [self cc_type]];
    }
    if (self.cc_number_enc != nil) {
        [nsString appendFormat:@"<cc_number_enc>%@</cc_number_enc>" , [self cc_number_enc]];
    }
    if (self.cc_last4 != nil) {
        [nsString appendFormat:@"<cc_last4>%@</cc_last4>" , [self cc_last4]];
    }
    if (self.cc_cid_enc != nil) {
        [nsString appendFormat:@"<cc_cid_enc>%@</cc_cid_enc>" , [self cc_cid_enc]];
    }
    if (self.cc_owner != nil) {
        [nsString appendFormat:@"<cc_owner>%@</cc_owner>" , [self cc_owner]];
    }
    if (self.cc_exp_month != nil) {
        [nsString appendFormat:@"<cc_exp_month>%@</cc_exp_month>" , [self cc_exp_month]];
    }
    if (self.cc_exp_year != nil) {
        [nsString appendFormat:@"<cc_exp_year>%@</cc_exp_year>" , [self cc_exp_year]];
    }
    if (self.cc_ss_owner != nil) {
        [nsString appendFormat:@"<cc_ss_owner>%@</cc_ss_owner>" , [self cc_ss_owner]];
    }
    if (self.cc_ss_start_month != nil) {
        [nsString appendFormat:@"<cc_ss_start_month>%@</cc_ss_start_month>" , [self cc_ss_start_month]];
    }
    if (self.cc_ss_start_year != nil) {
        [nsString appendFormat:@"<cc_ss_start_year>%@</cc_ss_start_year>" , [self cc_ss_start_year]];
    }
    if (self.cc_ss_issue != nil) {
        [nsString appendFormat:@"<cc_ss_issue>%@</cc_ss_issue>" , [self cc_ss_issue]];
    }
    if (self.po_number != nil) {
        [nsString appendFormat:@"<po_number>%@</po_number>" , [self po_number]];
    }
    if (self.additional_data != nil) {
        [nsString appendFormat:@"<additional_data>%@</additional_data>" , [self additional_data]];
    }
    if (self.additional_information != nil) {
        [nsString appendFormat:@"<additional_information>%@</additional_information>" , [self additional_information]];
    }
    if (addNameWrap == YES)
        [nsString appendString:@"</shoppingCartPaymentEntity>" ];
    return nsString;
}
#pragma mark - NSCoding
-(id)initWithCoder:(NSCoder *)decoder{
    self = [super init];
    if (self){
        self.payment_id = [decoder decodeObjectForKey:@"payment_id"];
        self.created_at = [decoder decodeObjectForKey:@"created_at"];
        self.updated_at = [decoder decodeObjectForKey:@"updated_at"];
        self.method = [decoder decodeObjectForKey:@"method"];
        self.cc_type = [decoder decodeObjectForKey:@"cc_type"];
        self.cc_number_enc = [decoder decodeObjectForKey:@"cc_number_enc"];
        self.cc_last4 = [decoder decodeObjectForKey:@"cc_last4"];
        self.cc_cid_enc = [decoder decodeObjectForKey:@"cc_cid_enc"];
        self.cc_owner = [decoder decodeObjectForKey:@"cc_owner"];
        self.cc_exp_month = [decoder decodeObjectForKey:@"cc_exp_month"];
        self.cc_exp_year = [decoder decodeObjectForKey:@"cc_exp_year"];
        self.cc_ss_owner = [decoder decodeObjectForKey:@"cc_ss_owner"];
        self.cc_ss_start_month = [decoder decodeObjectForKey:@"cc_ss_start_month"];
        self.cc_ss_start_year = [decoder decodeObjectForKey:@"cc_ss_start_year"];
        self.cc_ss_issue = [decoder decodeObjectForKey:@"cc_ss_issue"];
        self.po_number = [decoder decodeObjectForKey:@"po_number"];
        self.additional_data = [decoder decodeObjectForKey:@"additional_data"];
        self.additional_information = [decoder decodeObjectForKey:@"additional_information"];
    }
    return self;
}
-(void)encodeWithCoder:(NSCoder *)encoder{
    [encoder encodeObject:self.payment_id forKey:@"payment_id"];
    [encoder encodeObject:self.created_at forKey:@"created_at"];
    [encoder encodeObject:self.updated_at forKey:@"updated_at"];
    [encoder encodeObject:self.method forKey:@"method"];
    [encoder encodeObject:self.cc_type forKey:@"cc_type"];
    [encoder encodeObject:self.cc_number_enc forKey:@"cc_number_enc"];
    [encoder encodeObject:self.cc_last4 forKey:@"cc_last4"];
    [encoder encodeObject:self.cc_cid_enc forKey:@"cc_cid_enc"];
    [encoder encodeObject:self.cc_owner forKey:@"cc_owner"];
    [encoder encodeObject:self.cc_exp_month forKey:@"cc_exp_month"];
    [encoder encodeObject:self.cc_exp_year forKey:@"cc_exp_year"];
    [encoder encodeObject:self.cc_ss_owner forKey:@"cc_ss_owner"];
    [encoder encodeObject:self.cc_ss_start_month forKey:@"cc_ss_start_month"];
    [encoder encodeObject:self.cc_ss_start_year forKey:@"cc_ss_start_year"];
    [encoder encodeObject:self.cc_ss_issue forKey:@"cc_ss_issue"];
    [encoder encodeObject:self.po_number forKey:@"po_number"];
    [encoder encodeObject:self.additional_data forKey:@"additional_data"];
    [encoder encodeObject:self.additional_information forKey:@"additional_information"];
}
-(id)copyWithZone:(NSZone *)zone {
    shoppingCartPaymentEntity *finalCopy = [[[self class] allocWithZone: zone] init];
    
    NSString *copy1 = [self.payment_id copy];
    finalCopy.payment_id = copy1;
    
    NSString *copy2 = [self.created_at copy];
    finalCopy.created_at = copy2;
    
    NSString *copy3 = [self.updated_at copy];
    finalCopy.updated_at = copy3;
    
    NSString *copy4 = [self.method copy];
    finalCopy.method = copy4;
    
    NSString *copy5 = [self.cc_type copy];
    finalCopy.cc_type = copy5;
    
    NSString *copy6 = [self.cc_number_enc copy];
    finalCopy.cc_number_enc = copy6;
    
    NSString *copy7 = [self.cc_last4 copy];
    finalCopy.cc_last4 = copy7;
    
    NSString *copy8 = [self.cc_cid_enc copy];
    finalCopy.cc_cid_enc = copy8;
    
    NSString *copy9 = [self.cc_owner copy];
    finalCopy.cc_owner = copy9;
    
    NSString *copy10 = [self.cc_exp_month copy];
    finalCopy.cc_exp_month = copy10;
    
    NSString *copy11 = [self.cc_exp_year copy];
    finalCopy.cc_exp_year = copy11;
    
    NSString *copy12 = [self.cc_ss_owner copy];
    finalCopy.cc_ss_owner = copy12;
    
    NSString *copy13 = [self.cc_ss_start_month copy];
    finalCopy.cc_ss_start_month = copy13;
    
    NSString *copy14 = [self.cc_ss_start_year copy];
    finalCopy.cc_ss_start_year = copy14;
    
    NSString *copy15 = [self.cc_ss_issue copy];
    finalCopy.cc_ss_issue = copy15;
    
    NSString *copy16 = [self.po_number copy];
    finalCopy.po_number = copy16;
    
    NSString *copy17 = [self.additional_data copy];
    finalCopy.additional_data = copy17;
    
    NSString *copy18 = [self.additional_information copy];
    finalCopy.additional_information = copy18;
    
    return finalCopy;
}

@end
