//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 1.5
// Date Of Creation: 11/5/2013 1:51:25 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import "shoppingCartAddressEntity.h" 


@implementation shoppingCartAddressEntity

-(id)initWithArray:(NSArray*)array {
    self = [super init];
    if (self) {
        @try {
            for (int i0 = 0; i0 < [array count]; i0++)
            {
                if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"address_id"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setAddress_id:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"created_at"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCreated_at:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"updated_at"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setUpdated_at:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"customer_id"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCustomer_id:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"save_in_address_book"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setSave_in_address_book:[nodeContentValue intValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"save_in_address_bookSpecified"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setSave_in_address_bookSpecified:[nodeContentValue boolValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"customer_address_id"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCustomer_address_id:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"address_type"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setAddress_type:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"email"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setEmail:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"prefix"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setPrefix:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"firstname"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setFirstname:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"middlename"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setMiddlename:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"lastname"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setLastname:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"suffix"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setSuffix:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"company"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCompany:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"street"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setStreet:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"city"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCity:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"region"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setRegion:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"region_id"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setRegion_id:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"postcode"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setPostcode:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"country_id"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setCountry_id:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"telephone"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setTelephone:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"fax"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setFax:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"same_as_billing"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setSame_as_billing:[nodeContentValue intValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"same_as_billingSpecified"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setSame_as_billingSpecified:[nodeContentValue boolValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"free_shipping"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setFree_shipping:[nodeContentValue intValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"free_shippingSpecified"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setFree_shippingSpecified:[nodeContentValue boolValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"shipping_method"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setShipping_method:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"shipping_description"]==NSOrderedSame)){
                    NSString* nodeContentValue = [[NSString alloc] initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    if (nodeContentValue !=nil)
                        [self setShipping_description:nodeContentValue];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"weight"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setWeight:[nodeContentValue doubleValue]];
                }
                else if ( ([[array objectAtIndex:i0] objectForKey:@"nodeContent"] !=nil) &&  ([[[array objectAtIndex:i0]objectForKey:@"nodeName"]caseInsensitiveCompare:@"weightSpecified"]==NSOrderedSame)){
                    NSString *nodeContentValue = [[NSString alloc]initWithString:[[array objectAtIndex:i0] objectForKey:@"nodeContent"]];
                    [self setWeightSpecified:[nodeContentValue boolValue]];
                }
            }
        }
        @catch(NSException *ex){
        }
    }
    return self;
}
-(NSString*)toString:(BOOL)addNameWrap {
    NSMutableString *nsString = [NSMutableString string];
    if (addNameWrap == YES)
        [nsString appendString:@"<shoppingCartAddressEntity>" ];
    if (self.address_id != nil) {
        [nsString appendFormat:@"<address_id>%@</address_id>" , [self address_id]];
    }
    if (self.created_at != nil) {
        [nsString appendFormat:@"<created_at>%@</created_at>" , [self created_at]];
    }
    if (self.updated_at != nil) {
        [nsString appendFormat:@"<updated_at>%@</updated_at>" , [self updated_at]];
    }
    if (self.customer_id != nil) {
        [nsString appendFormat:@"<customer_id>%@</customer_id>" , [self customer_id]];
    }
    [nsString appendFormat:@"<save_in_address_book>%d</save_in_address_book>" , [self save_in_address_book]];
    [nsString appendFormat:@"<save_in_address_bookSpecified>%d</save_in_address_bookSpecified>" , [self save_in_address_bookSpecified]];
    if (self.customer_address_id != nil) {
        [nsString appendFormat:@"<customer_address_id>%@</customer_address_id>" , [self customer_address_id]];
    }
    if (self.address_type != nil) {
        [nsString appendFormat:@"<address_type>%@</address_type>" , [self address_type]];
    }
    if (self.email != nil) {
        [nsString appendFormat:@"<email>%@</email>" , [self email]];
    }
    if (self.prefix != nil) {
        [nsString appendFormat:@"<prefix>%@</prefix>" , [self prefix]];
    }
    if (self.firstname != nil) {
        [nsString appendFormat:@"<firstname>%@</firstname>" , [self firstname]];
    }
    if (self.middlename != nil) {
        [nsString appendFormat:@"<middlename>%@</middlename>" , [self middlename]];
    }
    if (self.lastname != nil) {
        [nsString appendFormat:@"<lastname>%@</lastname>" , [self lastname]];
    }
    if (self.suffix != nil) {
        [nsString appendFormat:@"<suffix>%@</suffix>" , [self suffix]];
    }
    if (self.company != nil) {
        [nsString appendFormat:@"<company>%@</company>" , [self company]];
    }
    if (self.street != nil) {
        [nsString appendFormat:@"<street>%@</street>" , [self street]];
    }
    if (self.city != nil) {
        [nsString appendFormat:@"<city>%@</city>" , [self city]];
    }
    if (self.region != nil) {
        [nsString appendFormat:@"<region>%@</region>" , [self region]];
    }
    if (self.region_id != nil) {
        [nsString appendFormat:@"<region_id>%@</region_id>" , [self region_id]];
    }
    if (self.postcode != nil) {
        [nsString appendFormat:@"<postcode>%@</postcode>" , [self postcode]];
    }
    if (self.country_id != nil) {
        [nsString appendFormat:@"<country_id>%@</country_id>" , [self country_id]];
    }
    if (self.telephone != nil) {
        [nsString appendFormat:@"<telephone>%@</telephone>" , [self telephone]];
    }
    if (self.fax != nil) {
        [nsString appendFormat:@"<fax>%@</fax>" , [self fax]];
    }
    [nsString appendFormat:@"<same_as_billing>%d</same_as_billing>" , [self same_as_billing]];
    [nsString appendFormat:@"<same_as_billingSpecified>%d</same_as_billingSpecified>" , [self same_as_billingSpecified]];
    [nsString appendFormat:@"<free_shipping>%d</free_shipping>" , [self free_shipping]];
    [nsString appendFormat:@"<free_shippingSpecified>%d</free_shippingSpecified>" , [self free_shippingSpecified]];
    if (self.shipping_method != nil) {
        [nsString appendFormat:@"<shipping_method>%@</shipping_method>" , [self shipping_method]];
    }
    if (self.shipping_description != nil) {
        [nsString appendFormat:@"<shipping_description>%@</shipping_description>" , [self shipping_description]];
    }
    [nsString appendFormat:@"<weight>%lf</weight>" , [self weight]];
    [nsString appendFormat:@"<weightSpecified>%d</weightSpecified>" , [self weightSpecified]];
    if (addNameWrap == YES)
        [nsString appendString:@"</shoppingCartAddressEntity>" ];
    return nsString;
}
#pragma mark - NSCoding
-(id)initWithCoder:(NSCoder *)decoder{
    self = [super init];
    if (self){
        self.address_id = [decoder decodeObjectForKey:@"address_id"];
        self.created_at = [decoder decodeObjectForKey:@"created_at"];
        self.updated_at = [decoder decodeObjectForKey:@"updated_at"];
        self.customer_id = [decoder decodeObjectForKey:@"customer_id"];
        self.save_in_address_book = [decoder decodeInt32ForKey:@"save_in_address_book"];
        self.save_in_address_bookSpecified = [decoder decodeInt32ForKey:@"save_in_address_bookSpecified"];
        self.customer_address_id = [decoder decodeObjectForKey:@"customer_address_id"];
        self.address_type = [decoder decodeObjectForKey:@"address_type"];
        self.email = [decoder decodeObjectForKey:@"email"];
        self.prefix = [decoder decodeObjectForKey:@"prefix"];
        self.firstname = [decoder decodeObjectForKey:@"firstname"];
        self.middlename = [decoder decodeObjectForKey:@"middlename"];
        self.lastname = [decoder decodeObjectForKey:@"lastname"];
        self.suffix = [decoder decodeObjectForKey:@"suffix"];
        self.company = [decoder decodeObjectForKey:@"company"];
        self.street = [decoder decodeObjectForKey:@"street"];
        self.city = [decoder decodeObjectForKey:@"city"];
        self.region = [decoder decodeObjectForKey:@"region"];
        self.region_id = [decoder decodeObjectForKey:@"region_id"];
        self.postcode = [decoder decodeObjectForKey:@"postcode"];
        self.country_id = [decoder decodeObjectForKey:@"country_id"];
        self.telephone = [decoder decodeObjectForKey:@"telephone"];
        self.fax = [decoder decodeObjectForKey:@"fax"];
        self.same_as_billing = [decoder decodeInt32ForKey:@"same_as_billing"];
        self.same_as_billingSpecified = [decoder decodeInt32ForKey:@"same_as_billingSpecified"];
        self.free_shipping = [decoder decodeInt32ForKey:@"free_shipping"];
        self.free_shippingSpecified = [decoder decodeInt32ForKey:@"free_shippingSpecified"];
        self.shipping_method = [decoder decodeObjectForKey:@"shipping_method"];
        self.shipping_description = [decoder decodeObjectForKey:@"shipping_description"];
        self.weight = [decoder decodeInt32ForKey:@"weight"];
        self.weightSpecified = [decoder decodeInt32ForKey:@"weightSpecified"];
    }
    return self;
}
-(void)encodeWithCoder:(NSCoder *)encoder{
    [encoder encodeObject:self.address_id forKey:@"address_id"];
    [encoder encodeObject:self.created_at forKey:@"created_at"];
    [encoder encodeObject:self.updated_at forKey:@"updated_at"];
    [encoder encodeObject:self.customer_id forKey:@"customer_id"];
    [encoder encodeInt32:self.save_in_address_book forKey:@"save_in_address_book"];
    [encoder encodeInt32:self.save_in_address_bookSpecified forKey:@"save_in_address_bookSpecified"];
    [encoder encodeObject:self.customer_address_id forKey:@"customer_address_id"];
    [encoder encodeObject:self.address_type forKey:@"address_type"];
    [encoder encodeObject:self.email forKey:@"email"];
    [encoder encodeObject:self.prefix forKey:@"prefix"];
    [encoder encodeObject:self.firstname forKey:@"firstname"];
    [encoder encodeObject:self.middlename forKey:@"middlename"];
    [encoder encodeObject:self.lastname forKey:@"lastname"];
    [encoder encodeObject:self.suffix forKey:@"suffix"];
    [encoder encodeObject:self.company forKey:@"company"];
    [encoder encodeObject:self.street forKey:@"street"];
    [encoder encodeObject:self.city forKey:@"city"];
    [encoder encodeObject:self.region forKey:@"region"];
    [encoder encodeObject:self.region_id forKey:@"region_id"];
    [encoder encodeObject:self.postcode forKey:@"postcode"];
    [encoder encodeObject:self.country_id forKey:@"country_id"];
    [encoder encodeObject:self.telephone forKey:@"telephone"];
    [encoder encodeObject:self.fax forKey:@"fax"];
    [encoder encodeInt32:self.same_as_billing forKey:@"same_as_billing"];
    [encoder encodeInt32:self.same_as_billingSpecified forKey:@"same_as_billingSpecified"];
    [encoder encodeInt32:self.free_shipping forKey:@"free_shipping"];
    [encoder encodeInt32:self.free_shippingSpecified forKey:@"free_shippingSpecified"];
    [encoder encodeObject:self.shipping_method forKey:@"shipping_method"];
    [encoder encodeObject:self.shipping_description forKey:@"shipping_description"];
    [encoder encodeInt32:self.weight forKey:@"weight"];
    [encoder encodeInt32:self.weightSpecified forKey:@"weightSpecified"];
}
-(id)copyWithZone:(NSZone *)zone {
    shoppingCartAddressEntity *finalCopy = [[[self class] allocWithZone: zone] init];
    
    NSString *copy1 = [self.address_id copy];
    finalCopy.address_id = copy1;
    
    NSString *copy2 = [self.created_at copy];
    finalCopy.created_at = copy2;
    
    NSString *copy3 = [self.updated_at copy];
    finalCopy.updated_at = copy3;
    
    NSString *copy4 = [self.customer_id copy];
    finalCopy.customer_id = copy4;
    
    finalCopy.save_in_address_book = self.save_in_address_book;
    
    finalCopy.save_in_address_bookSpecified = self.save_in_address_bookSpecified;
    
    NSString *copy7 = [self.customer_address_id copy];
    finalCopy.customer_address_id = copy7;
    
    NSString *copy8 = [self.address_type copy];
    finalCopy.address_type = copy8;
    
    NSString *copy9 = [self.email copy];
    finalCopy.email = copy9;
    
    NSString *copy10 = [self.prefix copy];
    finalCopy.prefix = copy10;
    
    NSString *copy11 = [self.firstname copy];
    finalCopy.firstname = copy11;
    
    NSString *copy12 = [self.middlename copy];
    finalCopy.middlename = copy12;
    
    NSString *copy13 = [self.lastname copy];
    finalCopy.lastname = copy13;
    
    NSString *copy14 = [self.suffix copy];
    finalCopy.suffix = copy14;
    
    NSString *copy15 = [self.company copy];
    finalCopy.company = copy15;
    
    NSString *copy16 = [self.street copy];
    finalCopy.street = copy16;
    
    NSString *copy17 = [self.city copy];
    finalCopy.city = copy17;
    
    NSString *copy18 = [self.region copy];
    finalCopy.region = copy18;
    
    NSString *copy19 = [self.region_id copy];
    finalCopy.region_id = copy19;
    
    NSString *copy20 = [self.postcode copy];
    finalCopy.postcode = copy20;
    
    NSString *copy21 = [self.country_id copy];
    finalCopy.country_id = copy21;
    
    NSString *copy22 = [self.telephone copy];
    finalCopy.telephone = copy22;
    
    NSString *copy23 = [self.fax copy];
    finalCopy.fax = copy23;
    
    finalCopy.same_as_billing = self.same_as_billing;
    
    finalCopy.same_as_billingSpecified = self.same_as_billingSpecified;
    
    finalCopy.free_shipping = self.free_shipping;
    
    finalCopy.free_shippingSpecified = self.free_shippingSpecified;
    
    NSString *copy28 = [self.shipping_method copy];
    finalCopy.shipping_method = copy28;
    
    NSString *copy29 = [self.shipping_description copy];
    finalCopy.shipping_description = copy29;
    
    finalCopy.weight = self.weight;
    
    finalCopy.weightSpecified = self.weightSpecified;
    
    return finalCopy;
}

@end
